### ISSUE TITLE
Find the smallest number in array 

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#1]
Given an array, find the smallest number with out using any for loops

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT, please assign this one to me.

**Comment by Sanjaykumar-IT** [comment]
> @Sanjaykumar-IT, please assign this one to me.

Assigned.

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , finished problem https://github.com/Sanjaykumar-IT/dsa-problems/pull/5

Please check!

**Comment by Sanjaykumar-IT** [comment]
Issue completed!
