### ISSUE TITLE
Remove duplicates from an array

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#11]
Given an array of arr[] of n integers, remove the duplicates from an array
Input [10,25,10,12,13,4,12]
Output [10,25,12,13,4]

**Comment by aravindhml** [comment]
Hi @Sanjaykumar-IT . Can you please assign this issue to me. Thanks.

**Comment by aravindhml** [comment]
Hi @Sanjaykumar-IT . Issue is resolved in this PR : https://github.com/Sanjaykumar-IT/dsa-problems/pull/12

**Comment by Sanjaykumar-IT** [comment]
Thanks @aravindhml
