### ISSUE TITLE
factorial of a number 

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#13]
Find the factorial of a number 
Input: 5 
Output: 120

**Comment by aravindhml** [comment]
Hi @Sanjaykumar-IT . Please assign this to me

**Comment by Sanjaykumar-IT** [comment]
> Hi @Sanjaykumar-IT . Please assign this to me

assigned

**Comment by aravindhml** [comment]
Hi @Sanjaykumar-IT . Issue is resolved in this PR : https://github.com/Sanjaykumar-IT/dsa-problems/pull/16
