### ISSUE TITLE
Get Binary number 

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#14]
Given a number n>1  in a decimal form print its binary form

Input 7
Output 111

**Comment by aravindhml** [comment]
Hi @Sanjaykumar-IT . Please assign this to me.

**Comment by aravindhml** [comment]
Issue is resolved in this PR: https://github.com/Sanjaykumar-IT/dsa-problems/pull/17

**Comment by Sanjaykumar-IT** [comment]
Issue completed!!
