### ISSUE TITLE
Find the missing number in an array

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#15]
Given an array with n consecutive numbers but there is one missing number. Return -1 if there is no missing number

Input [1,2,4,5] 
Output 3 

Input [1,2,3,4,5]
return -1

**Comment by aravindhml** [comment]
Hi @Sanjaykumar-IT . Please assign this to me.

**Comment by aravindhml** [comment]
Issue is resolved in this PR : https://github.com/Sanjaykumar-IT/dsa-problems/pull/18

**Comment by Sanjaykumar-IT** [comment]
Issue completed!!
