### ISSUE TITLE
Next Greater element in the given array

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#2]
Given an array, find the next greatest element and return an array 
return -1 if there is no greater element 
For Example, 
Input: [19, 12, 34,78,8]
Output: [34,34,78,-1,-1]

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , please assign this to me!

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , Created PR, https://github.com/Sanjaykumar-IT/dsa-problems/pull/8

Could you please review?

**Comment by Sanjaykumar-IT** [comment]
done!
