### ISSUE TITLE
Repeating element in the array

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#3]
Given an array, Find all the repeating elements 
Input: [1,3,4,1,3]
Output: [1,3] 
Input: [1,9,8,7]
Output: None /[]

**Comment by nitinryali** [comment]
Assign this to me @Sanjaykumar-IT

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , please assign this to me!

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , created PR https://github.com/Sanjaykumar-IT/dsa-problems/pull/9

Could you please review?

**Comment by Sanjaykumar-IT** [comment]
Done!

**Comment by Sanjaykumar-IT** [comment]
> @Sanjaykumar-IT , please assign this to me!
