### ISSUE TITLE
Product of the array except self 

### ISSUE THREAD

**Issue by Sanjaykumar-IT** [Sanjaykumar-IT/dsa-problems#4]
Given an array arr[] of n integers, construct a Product Array prod[] (of the same size) such that prod[i] is equal to the product of all the elements of arr[] except arr[i].   
Input: [10, 3, 5, 6, 2]
output:  [180, 600, 360, 300, 900]

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , please assign this one to me.

**Comment by Sanjaykumar-IT** [comment]
> @Sanjaykumar-IT , please assign this one to me.

Assigned

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , created PR https://github.com/Sanjaykumar-IT/dsa-problems/pull/10

Could you please review?

**Comment by Sanjaykumar-IT** [comment]
Issue completed
